service:
  web_server:
    image: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    networks:
      - mynetwork

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    restart: always
    depends_on:
      - postgres_server
    env_file: ../user_microservice/.env
    networks:
      - mynetwork
  python_api:
  bff:


networks:
  mynetwork:
    driver: bridge