services:
  postgres_server:
    image: postgres:latest
    container_name: postgres_server
    env_file:
      - ./config/postgre.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge